name: Publish README to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install markdown
        run: pip install markdown
      - name: Convert README to HTML
        run: |
          python -c "
          import markdown
          with open('README.md', 'r') as f:
              content = f.read()
          html = markdown.markdown(content)
          with open('index.html', 'w') as f:
              f.write(html)
          "
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: .
          clean: true
          token: ${{ secrets.GH_PAGES_DEPLOY }}
